docs: user tutorial for GCP NFS
kyma-project/cloud-manager pull request #332
Opened 2024-07-10 00:25 UTC by abalaie

**Description**

Changes proposed in this pull request:

- user tutorial for GCP NFS
- small changes to glossary
- small changes to gcpNfsVolume CRD document

**Related issue(s)**

2024-07-12 04:41 UTC, abalaie commented
Updated the document to be in sync with recent changes.

2024-07-15 11:33 UTC, mmitoraj commented on docs/user/tutorials/01-20-gcp-nfs-volume.md
> +   The command should print something like:
```suggestion
   The command should print a result similar to the following one:
```

2024-07-15 11:33 UTC, mmitoraj commented on docs/user/tutorials/01-20-gcp-nfs-volume.md
> +   Note that the content after `File content:` contains prints from both workloads. This
```suggestion
   >[!NOTE] The `File content:` contains prints from both workloads. This demonstrates the ReadWriteMany capability of the volume.
```

2024-07-15 11:33 UTC, mmitoraj commented on docs/user/tutorials/01-20-gcp-nfs-volume.md
> +   demonstrates the ReadWriteMany capability of the volume.
```suggestion
```

2024-07-15 11:33 UTC, mmitoraj commented on docs/user/tutorials/01-20-gcp-nfs-volume.md
> +6. Create two workloads that both write to the volume
```suggestion
6. Create two workloads that both write to the volume. Run:
```

2024-07-15 12:51 UTC, mmitoraj requested changes
Please also add the tutorial to the list in `_sidebar.md`.

2024-07-15 23:46 UTC, abalaie commented
I rebased the code as it had some conflicts with the base and the option was not available on the UI. 
But then it showed many commits that were already merged to the "main" branch. So based on Github suggestions on the same issue, I changed the base branch to something else and again back to main, so that the base branch commit get updated and it only shows the relevant changes. And it worked.

2024-07-16 11:43 UTC, tmilos77 approved these changes

2024-07-16 11:48 UTC, merged