chore(docs): moved technical to contributor/architecture
kyma-project/cloud-manager pull request #351
Opened 2024-07-15 09:53 UTC by tmilos77

**Description**

Changes proposed in this pull request:

- moved old `docs/technical` to `docs/contributor/architecture`

**Related issue(s)**

2024-07-15 11:20 UTC, mmitoraj commented on docs/contributor/architecture/README.md
> +Kyma CR in KCP to the Shoot CR in Garden it is possible to determine the cloud provider scope.
```suggestion
Kyma CR in KCP to the Shoot CR in Gardener it is possible to determine the cloud provider scope. 
```
Garden or Gardener?

2024-07-15 11:20 UTC, mmitoraj commented on docs/contributor/architecture/README.md
> +* improve performance by not reading so many different resources and reaching out to the Garden
```suggestion
* improve performance by not reading so many different resources and reaching out to Gardener
```
Gardener?

2024-07-15 11:20 UTC, mmitoraj commented on docs/contributor/architecture/README.md
> +* simply the development landscape by not avoiding the necessity to beside local KCP cluster also have the Garden cluster
```suggestion
* simplify the development landscape by not avoiding the necessity to beside the local KCP cluster and also have the Gardener cluster 
```
I'm not sure if I follow: "by not avoiding the necessity to beside the local KCP cluster". Can we rephrase?

2024-07-15 11:20 UTC, mmitoraj commented on docs/contributor/architecture/README.md
> +Upon the appearance of the first resource from certain SKR the cloud provider scope is determined, saved in the
```suggestion
Upon the appearance of the first resource from a certain SKR the cloud provider scope is determined, saved in the 
```

2024-07-15 11:20 UTC, mmitoraj commented on docs/contributor/architecture/README.md
> +Scope KCP resource, and original Cloud Control KCP resource updated with the `scopeRef`. In dev, scope determination
```suggestion
Scope KCP resource and the original Cloud Control KCP resource is updated with the `scopeRef`. In dev, scope determination 
```

2024-07-15 11:20 UTC, mmitoraj commented on docs/contributor/architecture/README.md
> +Some cloud resources require an allocation of the private IP, like NFS instance. Since network security is managed
```suggestion
Some cloud resources require an allocation of a private IP, like an NFS instance. Since network security is managed 
```

2024-07-15 14:19 UTC, mmitoraj approved these changes

2024-07-15 14:20 UTC, mmitoraj commented on docs/contributor/architecture/README.md
> +![SKR Controller Manager](./assets/skr-controller-manager.drawio.svg)
The extension in the source file needs also to be changed - they should match.

2024-07-15 14:21 UTC, mmitoraj requested changes
Please make the extensions for the diagram in the source file and the markdown document match.

2024-07-16 12:34 UTC, dushanpantic approved these changes

2024-07-16 12:42 UTC, merged