chore: upgrade k8s version to 1.31.0
kyma-project/cloud-manager pull request #827
Opened 2024-11-25 13:03 UTC by ijovovic

Changes proposed in this pull request:

- upgrade k8s version to 1.31.0

2024-11-25 17:27 UTC, dushanpantic reviewed
Should we update client-go as well?

2024-12-09 12:19 UTC, tmilos77 commented
> Should we update client-go as well?
Don't see it as necessary to be done together with this change. But eventually, yes, we should do that as well.

2024-12-09 12:20 UTC, tmilos77 requested changes
The change must be done here as well https://github.com/kyma-project/cloud-manager/blob/main/pkg/testinfra/run.go#L43

2024-12-16 12:57 UTC, tmilos77 approved these changes

2024-12-16 13:22 UTC, merged